name: 'PR Monitor'
description: 'Scan for open pull requests and send a Slack update'
inputs:
  channel:
    description: 'Channel to send to'
    required: true
    default: '#pr-monitor'
runs:
  using: 'node12'
  main: 'dist/index.js'
