name: 'PR Monitor'
description: 'Scan for open pull requests and send a Slack update'
inputs:
  channel:
    description: 'Channel to send to'
    required: true
    default: '#pr-monitor'
  slack-token:
    description: 'Oauth token to enable slack send'
    required: true
  sort:
    description: 'Field to sort by: can be created, updated, popularity (comment count) or long-running'
    required: true
    default: 'updated'
  sort-direction:
    description: 'Direction for sort'
    required: true
    default: 'desc'
runs:
  using: 'node12'
  main: 'dist/index.js'
